kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: food-delivery-cluster
nodes:
# one node hosting a control plane
- role: control-plane
  extraMounts:
  - hostPath: /home/jojo/.food-delivery-kind-volume
    containerPath: /persistent-volume